### ISSUE TITLE
Work on data

### ISSUE THREAD

**Issue by vishnuMohanan01** [RoboPiratesAGV/development_data#1]
## Tasks to carry out

- [ ] Rotate images if vertical
- [ ] Look at each image and verify it's similar to what will be in production - else replace the image.
- [ ] try loading images in grayscale
- [ ] try resizing images before labelling (preferrably less than 200 x 200)
> All the above steps before labelling
- [ ] load images in grayscale
- [ ] resize images 
- [ ] pickle loaded data and backup the pickle.

> Currently the data was loaded as is after compression using the [rename script](https://github.com/RoboPiratesAGV/image-compressor/blob/master/start.py). Size was almost 2000 x 2000 or even more.
> Colab Processor ran out - **25k steps as 4 batches would have taken around 18hrs**. But GPU limit exceeded and process terminated before that.

**Comment by vishnuMohanan01** [comment]
Project Aborted.
